name: Go

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Build
              env:
                  GITHUB_TOKEN: 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
                  GOPRIVATE: github.com/slukits/
              run: go build -v ./...

            - name: Test
              env:
                  GITHUB_TOKEN: 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
                  GOPRIVATE: github.com/slukits/
              run: |
                  git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
                  go test -race -cover ./...
