name: Go

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18

            - name: Build
              run: go build -v ./...

            - name: Prepare Testing
              env:
                GITHUB_TOKEN: ${{ secrets.GOUNIT }}
              run: git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"

            - name: Test
              env:
                GOPRIVATE: github.com/slukits/
              run: go test -race -cover ./...
